name: Adding comment to issues
on:
  issues:
    types: [opened]

jobs:
  add-comment-using-action:
    runs-on: ubuntu-latest
    steps:
      - name: Add comment to issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: gh issue comment $ISSUE_URL --body "This is a comment from a GitHub Action"
