name: Hello world
on: push:
  branches:
    - main
    workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, world!"
        shell: bash
      - uses: actions/checkout@v3
      - name: Upload artifact

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Say Goodbye
        run: echo "Goodbye, world!"
        shell: bash

  